### PR TITLE
[WIP] Postcss

### PR DESCRIPTION
**Pull request by kvz**
Also see https://github.com/transloadit/content/pull/640

### CODE REVIEW

**Comment by arturi** [comment]
My last commit seemed to be working for me locally, both in dev and prod (build command).

**Comment by arturi** [comment]
But it also required disabling webpack config override in: https://github.com/transloadit/content/pull/640/files#diff-6a2898f11939737e279437e02bdc4a3aR120

**Comment by kvz** [comment]
Hey Artur that’s great thanks for taking another stab at this. I think let’s just forget about overrides until we have a need then? Or do we already? Then we could take a closer look again

**Comment by arturi** [comment]
Yeah, I think we can add them if we do, it would be fine like this for now. Could you test this one more time? It worked for me last time I tried, but I’m not 100% sure it’s respecting browser configs. It did add the newest prefixes (:placeholder) just fine though.

**Comment by kvz** [comment]
I don't have the time, so i guess we'll test in production 😄

**Pull request merged**
